"""
PHANTOM-ECHO REVEAL v22 — Single Canonical Entry Point
Delegates entirely to main_v2.run_full_pipeline() so that
`--mode demo` and `--mode eval` use the SAME code path.

Bug-1 fix: dual entry-point confusion eliminated.
"""

import argparse, json, logging, subprocess, sys
from pathlib import Path

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="PHANTOM-ECHO REVEAL Pipeline")
    parser.add_argument("--mode", choices=["demo", "eval", "single-frame", "realtime", "agent"], default="demo")
    parser.add_argument("--output", default="output")
    parser.add_argument("--scenes", nargs="+",
                        default=["living_room_01", "office_01", "bedroom_01"])
    args = parser.parse_args()

    if args.mode == "demo":
        import os
        os.environ.setdefault("PHANTOM_OUTPUT", args.output)
        from src.main_v2 import run_full_pipeline, OUTPUT_DIR
        summary = run_full_pipeline()
        # v23 fix (report finding 4): actually WRITE summary.json so the
        # committed output reproduces a clean run (previously only printed).
        summary.setdefault("_note", "Regenerated by `python -m src.main --mode demo` (v23).")
        with open(os.path.join(OUTPUT_DIR, "summary.json"), "w") as _f:
            json.dump(summary, _f, indent=2, default=str)
        print(json.dumps(summary, indent=2, default=str))
        print(f"\nWrote {os.path.join(OUTPUT_DIR, 'summary.json')}")
        print("Live dashboard: python -m src.main --mode realtime  ->  http://localhost:8000")

    elif args.mode == "eval":
        # Bug-CE7 fix: call run_eval (real pipeline), not old evaluate.py
        result = subprocess.run(
            [sys.executable, "-m", "src.eval.run_eval",
             "--output", args.output,
             "--scenes"] + args.scenes,
            capture_output=False
        )
        sys.exit(result.returncode)

    elif args.mode == "realtime":
        # v22: live streaming dashboard (FastAPI + WebSocket + Three.js)
        import os
        os.environ.setdefault("PHANTOM_OUTPUT", args.output)
        import uvicorn
        print("PHANTOM-ECHO REVEAL — live dashboard at http://localhost:8000")
        uvicorn.run("src.realtime.server:app", host="0.0.0.0", port=8000)

    elif args.mode == "agent":
        # Agentic layer: a Prove→Measure→Imagine planner that calls the pipeline's
        # own modules as tools to resolve each unknown region (reasoning trace +
        # per-region tag). Deterministic offline by default; set
        # PHANTOM_AGENT_LLM=claude (+ ANTHROPIC_API_KEY) for the Claude planner.
        import os
        os.environ.setdefault("PHANTOM_OUTPUT", args.output)
        from src.agent import run_agent
        result = run_agent()
        out_path = os.path.join(args.output, "agent_trace.json")
        os.makedirs(args.output, exist_ok=True)
        with open(out_path, "w") as _f:
            json.dump(result.to_dict(), _f, indent=2, default=str)
        print("\n" + "=" * 60)
        print(f"AGENT ({result.planner}) resolved {len(result.regions)} regions "
              f"in {result.steps} tool-steps, {result.elapsed_s}s")
        for rid, tag in result.regions.items():
            print(f"  {rid:16s} -> {tag}")
        print(f"  tool use: {result.tool_use_counts}")
        print(f"\nReasoning trace written to {out_path}")

    elif args.mode == "single-frame":
        from src.main_v2 import run_full_pipeline
        summary = run_full_pipeline(n_frames=1)
        # BUG-V18-5 FIX: run_full_pipeline returns 'counts' dict, not 'n_gaussians_visible'
        _counts = summary.get('counts', {})
        _total  = sum(_counts.values()) if _counts else 0
        logger.info(f"Single frame: {_total} Gaussians {_counts}")


if __name__ == "__main__":
    main()
